# Generated by Django 3.2.5 on 2021-07-30 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveBigIntegerField(default=0, verbose_name='Число просмотров')),
                ('likes', models.PositiveBigIntegerField(default=0, verbose_name='Число лайков')),
                ('dislikes', models.PositiveBigIntegerField(default=0, verbose_name='Число дизлайков')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': ['-views'],
            },
        ),
        migrations.CreateModel(
            name='ImageWithContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано?')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('statistic', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='imagesApp.imagestatistic')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Изображение с содержимым',
                'verbose_name_plural': 'Изображения с содержимым',
                'ordering': ['-created_at'],
            },
        ),
    ]
